# Generated by Django 3.2.8 on 2021-11-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
